services:
  - type: web
    name: blockcert-ai
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 200 --workers 1
    envVars:
      - key: TOKENIZERS_PARALLELISM
        value: "false"
      - key: PYTHON_VERSION
        value: "3.13"
